### ISSUE TITLE
Undefined variable when using  "postcss-simple-vars": "^6.0.3"

### ISSUE THREAD

**Issue by anlijiu** [madyankin/postcss-each#35]
:root {
  --grid-breakpoints-values      : (0, 576px, 768px, 992px, 1200px);
}

@each $value in var(--grid-breakpoints-values) {
  @media (min-width: $value) {
      .heading {}
  }
}

in function variable (variables, node, str, name, opts, result)  of postcss-simple-vars/index.js
I print  variables and name ,  found the name is "value", not actual value in --grid-breakpoints-values

**Comment by nestor-diaz** [comment]
@anlijiu may I know how did you solve this please? I'm running into a similar issue but haven't found a fix. Thanks.
