### ISSUE TITLE
postcss-simple-vars postcss7.0.14 installed to postcss-each node_modules

### ISSUE THREAD

**Issue by Joeycz** [madyankin/postcss-each#36]
![image](https://user-images.githubusercontent.com/7298176/110736192-32790880-8266-11eb-8e54-d87d3c65dab5.png)

### my env:
node: v12.18.3
npm: 6.14.6
os: macos 11.2.1

package.json
{
  "name": "",
  "version": "0.0.0",
  "description": "",
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "dependencies": {
    "vue": "^3.0.7",
    "vue-router": "^4.0.4",
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.16.1",
    "@typescript-eslint/parser": "^4.16.1",
    "@vitejs/plugin-vue": "^1.1.5",
    "@vue/compiler-sfc": "^3.0.7",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vuedx/typecheck": "^0.6.3",
    "@vuedx/typescript-plugin-vue": "^0.6.3",
    "eslint": "^7.21.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.7.0",
    "husky": "^4.3.8",
    "lint-staged": "^10.5.4",
    "postcss": "^8.2.8",
    "postcss-advanced-variables": "^3.0.1",
    "postcss-at-rules-variables": "^0.2.1",
    "postcss-bem-fix": "^2.1.0",
    "postcss-calc": "^8.0.0",
    "postcss-clear-empty-strings": "^1.0.0",
    "postcss-discard-comments": "^4.0.2",
    "postcss-discard-duplicates": "^4.0.2",
    "postcss-discard-empty": "^4.0.1",
    "postcss-discard-empty-nightly": "^0.8.4",
    "postcss-each": "^1.0.0",
    "postcss-each-variables": "^0.3.0",
    "postcss-extend": "^1.0.5",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-for": "^2.1.1",
    "postcss-import": "^14.0.0",
    "postcss-mixins": "^7.0.3",
    "postcss-nested": "^5.0.4",
    "postcss-preset-env": "^6.7.0",
    "postcss-pxtorem": "^5.1.1",
    "postcss-short": "^5.0.0",
    "postcss-simple-vars": "^6.0.3",
    "postcss-units": "^1.2.1",
    "prettier": "^2.2.1",
    "typescript": "^4.2.2",
    "vite": "^2.0.5"
  }
}

when I `npm install`, postcss-each can not work ok

**Comment by madyankin** [comment]
Fixed in https://github.com/madyankin/postcss-each/pull/38
